on region enter:
    set {_temp::list::*} to size of {red::team::*} and size of {blue::team::*}
    set {_temp::list::*} to sorted {_temp::list::*}
    set {max::team::size} to {_temp::list::2}
    if {_temp::list::1} >= {max::team::size} - 1:
        if {_temp::list::2} >= {max::team::size} - 1:
            add 1 to {max::team::size}
    if "%region%" is "red_team in world ctf":
        if {red::team::*} contains player:
            teleport player to red_spawn()
        else if size of {red::team::*} < {max::team::size}:
            teleport player to red_spawn()
            remove_player_from_team(player)
            add player to {red::team::*}
        else:
            teleport player to team_choosing_spawn()
    else if "%region%" is "blue_team in world ctf":
        if {blue::team::*} contains player:
            teleport player to blue_spawn()
        else if size of {blue::team::*} < {max::team::size}:
            teleport player to blue_spawn()
            remove_player_from_team(player)
            add player to {blue::team::*}
        else:
            teleport player to team_choosing_spawn()
