every 1 second:
    if {event::timer::*} is set:
        set {event::timer::minutes} to rounded down ({event::timer::time} / 60)
        set {event::timer::seconds} to ({event::timer::time} - ({event::timer::minutes} * 60))
        if {event::timer::time} is greater than 0:
            subtract 1 from {event::timer::time}
        else:
            delete {event::timer::*}

function gettimer() :: string:
    if {event::timer::*} is set:
        if {event::timer::minutes} is greater than 0:
            if {event::timer::seconds} is greater than 0:
                if {event::timer::seconds} is not greater than 9:
                    return "%{event::timer::minutes}%:0%{event::timer::seconds}%"
                else:
                    return "%{event::timer::minutes}%:%{event::timer::seconds}%"
            else:
                return "%{event::timer::minutes}%:00"
        else:
            if {event::timer::seconds} is greater than 0:
                if {event::timer::seconds} is not greater than 9:
                    return "0:0%{event::timer::seconds}%"
                else:
                    return "0:%{event::timer::seconds}%"
            else:
                return "0:00"
    else:
        return "0:00"
