command /craft:
    trigger:
        if player has permission "recipes.red":
            execute player command "/redcraft1"
            stop
        else if player has permission "recipes.blue":
            execute player command "/bluecraft1"
            stop
        else if player has permission "recipes.green":
            execute player command "/greencraft1"
            stop
        else if player has permission "recipes.yellow":
            execute player command "/yellowcraft1"
            stop

command /crafts:
    trigger:
        if player has permission "recipes.red":
            execute player command "/redcraft1"
            stop
        else if player has permission "recipes.blue":
            execute player command "/bluecraft1"
            stop
        else if player has permission "recipes.green":
            execute player command "/greencraft1"
            stop
        else if player has permission "recipes.yellow":
            execute player command "/yellowcraft1"
            stop

command /recipe:
    trigger:
        if player has permission "recipes.red":
            execute player command "/redcraft1"
            stop
        else if player has permission "recipes.blue":
            execute player command "/bluecraft1"
            stop
        else if player has permission "recipes.green":
            execute player command "/greencraft1"
            stop
        else if player has permission "recipes.yellow":
            execute player command "/yellowcraft1"
            stop

command /recipes:
    trigger:
        if player has permission "recipes.red":
            execute player command "/redcraft1"
            stop
        else if player has permission "recipes.blue":
            execute player command "/bluecraft1"
            stop
        else if player has permission "recipes.green":
            execute player command "/greencraft1"
            stop
        else if player has permission "recipes.yellow":
            execute player command "/yellowcraft1"
            stop

on load:
    set {_red1} to unbreakable netherite sword named "&cKnight's Sword" with lore "&4Best Sword!" with hidden enchants flag with custom model data 10701
    enchant {_red1} with sharpness 1
    register new shaped recipe for {_red1} using redstone dust, iron block, redstone dust, diamond block, diamond sword, diamond block, redstone dust, gold block and redstone dust with id "red1"
    set {_red2} to unbreakable bow named "&fKnight's Bow" with lore "&7Infinity 1" and "&7Punch 1" with hidden enchants flag with custom model data 1000
    enchant {_red2} with infinity 1 and punch 1
    register new shaped recipe for {_red2} using air, iron block, iron ingot, diamond block, bow, iron ingot, air, gold block and iron ingot with id "red2"
    set {_red3} to unbreakable shield named "&cKnight's Shield" with lore "&4Best Shield!" with hidden enchants flag with custom model data 601
    enchant {_red3} with mending 1
    register new shaped recipe for {_red3} using redstone dust, iron ingot, redstone dust, iron ingot, shield, iron ingot, redstone dust, iron ingot and redstone dust with id "red3"
    set {_red4} to golden carrot named "&fIron Bread" with lore "&43 Hunger Bars" with custom model data 32279
    register new shaped recipe for {_red4} using iron nugget, iron nugget, iron nugget, wheat seeds, wheat seeds, wheat seeds, iron nugget, iron nugget and iron nugget with id "red4"
    set {_red5} to cooked beef named "&6Gold Bread" with lore "&44 Hunger Bars" with custom model data 52479
    register new shaped recipe for {_red5} using gold nugget, gold nugget, gold nugget, wheat seeds, wheat seeds, wheat seeds, gold nugget, gold nugget and gold nugget with id "red5"
    set {_red6} to unbreakable diamond helmet named "&fKnight's Helmet" with lore "&7Protection 3" with hidden enchants flag with custom model data 1000
    enchant {_red6} with protection 3
    dye {_red6} (255, 255, 255)
    register new shaped recipe for {_red6} using air, diamond block, air, iron block, diamond helmet, iron block, air, gold block and air with id "red6"
    set {_red7} to unbreakable diamond chestplate named "&fKnight's Chestplate" with lore "&7Protection 3" with hidden enchants flag with custom model data 1000
    enchant {_red7} with protection 3
    dye {_red7} (255, 255, 255)
    register new shaped recipe for {_red7} using iron block, iron block, iron block, diamond block, diamond chestplate, diamond block, gold block, gold block and gold block with id "red7"
    set {_red8} to unbreakable diamond leggings named "&fKnight's Leggings" with lore "&7Protection 3" with hidden enchants flag with custom model data 1000
    enchant {_red8} with protection 3
    dye {_red8} (255, 255, 255)
    register new shaped recipe for {_red8} using air, diamond block, air, diamond, diamond leggings, diamond, gold block, iron block and gold block with id "red8"
    set {_red9} to unbreakable diamond boots named "&fKnight's Boots" with lore "&7Protection 3" with hidden enchants flag with custom model data 1000
    enchant {_red9} with protection 3
    dye {_red9} (255, 255, 255)
    register new shaped recipe for {_red9} using air, diamond block, air, iron block, diamond boots, iron block, air, gold block and air with id "red9"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    set {_blue1} to unbreakable netherite sword named "&9Knight's Sword" with lore "&3Best Sword!" with hidden enchants flag with custom model data 10702
    enchant {_blue1} with sharpness 1
    register new shaped recipe for {_blue1} using lapis lazuli, iron block, lapis lazuli, diamond block, diamond sword, diamond block, lapis lazuli, gold block and lapis lazuli with id "blue1"
    set {_blue2} to unbreakable shield named "&9Knight's Shield" with lore "&3Best Shield!" with hidden enchants flag with custom model data 602
    enchant {_blue2} with mending 1
    register new shaped recipe for {_blue2} using lapis lazuli, iron ingot, lapis lazuli, iron ingot, shield, iron ingot, lapis lazuli, iron ingot and lapis lazuli with id "blue2"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    set {_green1} to unbreakable netherite sword named "&aKnight's Sword" with lore "&2Best Sword!" with hidden enchants flag with custom model data 10703
    enchant {_green1} with sharpness 1
    register new shaped recipe for {_green1} using emerald, iron block, emerald, diamond block, diamond sword, diamond block, emerald, gold block and emerald with id "green1"
    set {_green2} to unbreakable shield named "&aKnight's Shield" with lore "&2Best Shield!" with hidden enchants flag with custom model data 603
    enchant {_green2} with mending 1
    register new shaped recipe for {_green2} using emerald, iron ingot, emerald, iron ingot, shield, iron ingot, emerald, iron ingot and emerald with id "green2"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
    set {_yellow1} to unbreakable netherite sword named "&eKnight's Sword" with lore "&6Best Sword!" with hidden enchants flag with custom model data 10704
    enchant {_yellow1} with sharpness 1
    register new shaped recipe for {_yellow1} using raw gold, iron block, raw gold, diamond block, diamond sword, diamond block, raw gold, gold block and raw gold with id "yellow1"
    set {_yellow2} to unbreakable shield named "&eKnight's Shield" with lore "&6Best Shield!" with hidden enchants flag with custom model data 604
    enchant {_yellow2} with mending 1
    register new shaped recipe for {_yellow2} using raw gold, iron ingot, raw gold, iron ingot, shield, iron ingot, raw gold, iron ingot and raw gold with id "yellow2"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /redcraft1:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red1" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red1" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "Red1" of player to redstone dust
        set slot 12 of metadata tag "Red1" of player to iron block
        set slot 13 of metadata tag "Red1" of player to redstone dust
        set slot 20 of metadata tag "Red1" of player to diamond block
        set slot 21 of metadata tag "Red1" of player to diamond sword
        set slot 22 of metadata tag "Red1" of player to diamond block
        set slot 29 of metadata tag "Red1" of player to redstone dust
        set slot 30 of metadata tag "Red1" of player to gold block
        set slot 31 of metadata tag "Red1" of player to redstone dust
        set slot 24 of metadata tag "Red1" of player to unbreakable netherite sword of sharpness 1 with hidden enchants flag named "&cKnight's Sword" with lore "&4Best Sword!" with custom model data 10701
        set slot 44 of metadata tag "Red1" of player to paper named "&a&lＰＡＧＥ &a2" with custom model data 1013
        open (metadata tag "Red1" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red1" of player):
        cancel event 
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft2"

command /redcraft2:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red2" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red2" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "Red2" of player to iron block
        set slot 13 of metadata tag "Red2" of player to iron ingot
        set slot 20 of metadata tag "Red2" of player to diamond block
        set slot 21 of metadata tag "Red2" of player to bow
        set slot 22 of metadata tag "Red2" of player to iron ingot
        set slot 30 of metadata tag "Red2" of player to gold block
        set slot 31 of metadata tag "Red2" of player to iron ingot
        set slot 24 of metadata tag "Red2" of player to unbreakable bow of efficiency 1 with hidden enchants flag named "&cKnight's Bow" with lore "&4Infinity 1" and "&4Punch 1" with custom model data 1000
        set slot 36 of metadata tag "Red2" of player to paper named "&c&lＰＡＧＥ &c1" with custom model data 1014
        set slot 44 of metadata tag "Red2" of player to paper named "&a&lＰＡＧＥ &a3" with custom model data 1013
        open (metadata tag "Red2" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red2" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft1"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft3"

command /redcraft3:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red3" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red3" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "Red3" of player to redstone dust
        set slot 12 of metadata tag "Red3" of player to iron ingot
        set slot 13 of metadata tag "Red3" of player to redstone dust
        set slot 20 of metadata tag "Red3" of player to iron ingot
        set slot 21 of metadata tag "Red3" of player to shield
        set slot 22 of metadata tag "Red3" of player to iron ingot
        set slot 29 of metadata tag "Red3" of player to redstone dust
        set slot 30 of metadata tag "Red3" of player to iron ingot
        set slot 31 of metadata tag "Red3" of player to redstone dust
        set slot 24 of metadata tag "Red3" of player to unbreakable shield of unbreaking 3 with hidden enchants flag named "&cRed Shield" with lore "&4Best Shield" with custom model data 601
        set slot 36 of metadata tag "Red3" of player to paper named "&c&lＰＡＧＥ &c2" with custom model data 1014
        set slot 44 of metadata tag "Red3" of player to paper named "&a&lＰＡＧＥ &a4" with custom model data 1013
        open (metadata tag "Red3" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red3" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft2"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft4"

command /redcraft4:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red4" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red4" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "Red4" of player to iron nugget
        set slot 12 of metadata tag "Red4" of player to iron nugget
        set slot 13 of metadata tag "Red4" of player to iron nugget
        set slot 20 of metadata tag "Red4" of player to wheat seeds
        set slot 21 of metadata tag "Red4" of player to wheat seeds
        set slot 22 of metadata tag "Red4" of player to wheat seeds
        set slot 29 of metadata tag "Red4" of player to iron nugget
        set slot 30 of metadata tag "Red4" of player to iron nugget
        set slot 31 of metadata tag "Red4" of player to iron nugget
        set slot 24 of metadata tag "Red4" of player to golden carrot named "&fIron Bread" with lore "&43 Hunger Bars" with custom model data 32279
        set slot 36 of metadata tag "Red4" of player to paper named "&c&lＰＡＧＥ &c3" with custom model data 1014
        set slot 44 of metadata tag "Red4" of player to paper named "&a&lＰＡＧＥ &a5" with custom model data 1013
        open (metadata tag "Red4" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red4" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft3"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft5"

command /redcraft5:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red5" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red5" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "Red5" of player to gold nugget
        set slot 12 of metadata tag "Red5" of player to gold nugget
        set slot 13 of metadata tag "Red5" of player to gold nugget
        set slot 20 of metadata tag "Red5" of player to wheat seeds
        set slot 21 of metadata tag "Red5" of player to wheat seeds                     
        set slot 22 of metadata tag "Red5" of player to wheat seeds
        set slot 29 of metadata tag "Red5" of player to gold nugget
        set slot 30 of metadata tag "Red5" of player to gold nugget
        set slot 31 of metadata tag "Red5" of player to gold nugget
        set slot 24 of metadata tag "Red5" of player to cooked beef named "&6Gold Bread" with lore "&44 Hunger Bars" with custom model data 52479
        set slot 36 of metadata tag "Red5" of player to paper named "&c&lＰＡＧＥ &c4" with custom model data 1014
        set slot 44 of metadata tag "Red5" of player to paper named "&a&lＰＡＧＥ &a6" with custom model data 1013
        open (metadata tag "Red5" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red5" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft4"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft6"

command /redcraft6:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red6" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red6" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "Red6" of player to diamond block
        set slot 20 of metadata tag "Red6" of player to iron block
        set slot 21 of metadata tag "Red6" of player to diamond helmet
        set slot 22 of metadata tag "Red6" of player to iron block
        set slot 30 of metadata tag "Red6" of player to gold block
        set slot 24 of metadata tag "Red6" of player to unbreakable leather helmet of protection 3 with hidden enchants flag with hidden attributes flag named "&cKnight's Helmet" with lore "&4Protection 3" and "&4Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "Red6" of player to paper named "&c&lＰＡＧＥ &c5" with custom model data 1014
        set slot 44 of metadata tag "Red6" of player to paper named "&a&lＰＡＧＥ &a7" with custom model data 1013
        open (metadata tag "Red6" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red6" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft5"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft7"

command /redcraft7:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red7" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red7" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "Red7" of player to iron block
        set slot 12 of metadata tag "Red7" of player to iron block
        set slot 13 of metadata tag "Red7" of player to iron block
        set slot 20 of metadata tag "Red7" of player to diamond block
        set slot 21 of metadata tag "Red7" of player to diamond chestplate
        set slot 22 of metadata tag "Red7" of player to diamond block
        set slot 29 of metadata tag "Red7" of player to gold block
        set slot 30 of metadata tag "Red7" of player to gold block
        set slot 31 of metadata tag "Red7" of player to gold block
        set slot 24 of metadata tag "Red7" of player to unbreakable leather chestplate of protection 3 with hidden enchants flag with hidden attributes flag named "&cKnight's Chestplate" with lore "&4Protection 3" and "&4Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "Red7" of player to paper named "&c&lＰＡＧＥ &c6" with custom model data 1014
        set slot 44 of metadata tag "Red7" of player to paper named "&a&lＰＡＧＥ &a8" with custom model data 1013
        open (metadata tag "Red7" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red7" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft6"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft8"

command /redcraft8:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red8" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red8" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "Red8" of player to diamond block
        set slot 20 of metadata tag "Red8" of player to diamond
        set slot 21 of metadata tag "Red8" of player to diamond leggings
        set slot 22 of metadata tag "Red8" of player to diamond
        set slot 29 of metadata tag "Red8" of player to gold block
        set slot 30 of metadata tag "Red8" of player to iron block
        set slot 31 of metadata tag "Red8" of player to gold block
        set slot 24 of metadata tag "Red8" of player to unbreakable leather leggings of protection 3 with hidden enchants flag with hidden attributes flag named "&cKnight's Leggings" with lore "&4Protection 3" and "&4Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "Red8" of player to paper named "&c&lＰＡＧＥ &c7" with custom model data 1014
        set slot 44 of metadata tag "Red8" of player to paper named "&a&lＰＡＧＥ &a9" with custom model data 1013
        open (metadata tag "Red8" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red8" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft7"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft9"

command /redcraft9:
    permission: recipes.red
    permission message: &cNeed To Be Red Team!
    trigger:
        wait 1 tick
        set metadata tag "Red9" of player to chest inventory with 5 rows named "&4&lＲＥＤ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "Red9" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "Red9" of player to diamond block
        set slot 20 of metadata tag "Red9" of player to iron block
        set slot 21 of metadata tag "Red9" of player to diamond boots
        set slot 22 of metadata tag "Red9" of player to iron block
        set slot 30 of metadata tag "Red9" of player to gold block
        set slot 24 of metadata tag "Red9" of player to unbreakable leather boots of protection 3 with hidden enchants flag with hidden attributes flag named "&cKnight's Boots" with lore "&4Protection 3" and "&4Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "Red9" of player to paper named "&c&lＰＡＧＥ &c8" with custom model data 1014
        open (metadata tag "Red9" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "Red9" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/redcraft8"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /bluecraft1:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue1" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue1" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "blue1" of player to lapis lazuli
        set slot 12 of metadata tag "blue1" of player to iron block
        set slot 13 of metadata tag "blue1" of player to lapis lazuli
        set slot 20 of metadata tag "blue1" of player to diamond block
        set slot 21 of metadata tag "blue1" of player to diamond sword
        set slot 22 of metadata tag "blue1" of player to diamond block
        set slot 29 of metadata tag "blue1" of player to lapis lazuli
        set slot 30 of metadata tag "blue1" of player to gold block
        set slot 31 of metadata tag "blue1" of player to lapis lazuli
        set slot 24 of metadata tag "blue1" of player to unbreakable netherite sword of sharpness 1 with hidden enchants flag named "&9Knight's Sword" with lore "&3Best Sword!" with custom model data 10702
        set slot 44 of metadata tag "blue1" of player to paper named "&a&lＰＡＧＥ &a2" with custom model data 1013
        open (metadata tag "blue1" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue1" of player):
        cancel event 
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft2"

command /bluecraft2:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue2" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue2" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "blue2" of player to iron block
        set slot 13 of metadata tag "blue2" of player to iron ingot
        set slot 20 of metadata tag "blue2" of player to diamond block
        set slot 21 of metadata tag "blue2" of player to bow
        set slot 22 of metadata tag "blue2" of player to iron ingot
        set slot 30 of metadata tag "blue2" of player to gold block
        set slot 31 of metadata tag "blue2" of player to iron ingot
        set slot 24 of metadata tag "blue2" of player to unbreakable bow of efficiency 1 with hidden enchants flag named "&9Knight's Bow" with lore "&3Infinity 1" and "&3Punch 1" with custom model data 1000
        set slot 36 of metadata tag "blue2" of player to paper named "&c&lＰＡＧＥ &c1" with custom model data 1014
        set slot 44 of metadata tag "blue2" of player to paper named "&a&lＰＡＧＥ &a3" with custom model data 1013
        open (metadata tag "blue2" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue2" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft1"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft3"

command /bluecraft3:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue3" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue3" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "blue3" of player to lapis lazuli
        set slot 12 of metadata tag "blue3" of player to iron ingot
        set slot 13 of metadata tag "blue3" of player to lapis lazuli
        set slot 20 of metadata tag "blue3" of player to iron ingot
        set slot 21 of metadata tag "blue3" of player to shield
        set slot 22 of metadata tag "blue3" of player to iron ingot
        set slot 29 of metadata tag "blue3" of player to lapis lazuli
        set slot 30 of metadata tag "blue3" of player to iron ingot
        set slot 31 of metadata tag "blue3" of player to lapis lazuli
        set slot 24 of metadata tag "blue3" of player to unbreakable shield of unbreaking 3 with hidden enchants flag named "&9Blue Shield" with lore "&3Best Shield" with custom model data 602
        set slot 36 of metadata tag "blue3" of player to paper named "&c&lＰＡＧＥ &c2" with custom model data 1014
        set slot 44 of metadata tag "blue3" of player to paper named "&a&lＰＡＧＥ &a4" with custom model data 1013
        open (metadata tag "blue3" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue3" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft2"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft4"

command /bluecraft4:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue4" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue4" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "blue4" of player to iron nugget
        set slot 12 of metadata tag "blue4" of player to iron nugget
        set slot 13 of metadata tag "blue4" of player to iron nugget
        set slot 20 of metadata tag "blue4" of player to wheat seeds
        set slot 21 of metadata tag "blue4" of player to wheat seeds
        set slot 22 of metadata tag "blue4" of player to wheat seeds
        set slot 29 of metadata tag "blue4" of player to iron nugget
        set slot 30 of metadata tag "blue4" of player to iron nugget
        set slot 31 of metadata tag "blue4" of player to iron nugget
        set slot 24 of metadata tag "blue4" of player to golden carrot named "&fIron Bread" with lore "&33 Hunger Bars" with custom model data 32279
        set slot 36 of metadata tag "blue4" of player to paper named "&c&lＰＡＧＥ &c3" with custom model data 1014
        set slot 44 of metadata tag "blue4" of player to paper named "&a&lＰＡＧＥ &a5" with custom model data 1013
        open (metadata tag "blue4" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue4" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft3"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft5"

command /bluecraft5:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue5" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue5" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "blue5" of player to gold nugget
        set slot 12 of metadata tag "blue5" of player to gold nugget
        set slot 13 of metadata tag "blue5" of player to gold nugget
        set slot 20 of metadata tag "blue5" of player to wheat seeds
        set slot 21 of metadata tag "blue5" of player to wheat seeds                     
        set slot 22 of metadata tag "blue5" of player to wheat seeds
        set slot 29 of metadata tag "blue5" of player to gold nugget
        set slot 30 of metadata tag "blue5" of player to gold nugget
        set slot 31 of metadata tag "blue5" of player to gold nugget
        set slot 24 of metadata tag "blue5" of player to cooked beef named "&6Gold Bread" with lore "&34 Hunger Bars" with custom model data 52479
        set slot 36 of metadata tag "blue5" of player to paper named "&c&lＰＡＧＥ &c4" with custom model data 1014
        set slot 44 of metadata tag "blue5" of player to paper named "&a&lＰＡＧＥ &a6" with custom model data 1013
        open (metadata tag "blue5" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue5" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft4"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft6"

command /bluecraft6:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue6" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue6" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "blue6" of player to diamond block
        set slot 20 of metadata tag "blue6" of player to iron block
        set slot 21 of metadata tag "blue6" of player to diamond helmet
        set slot 22 of metadata tag "blue6" of player to iron block
        set slot 30 of metadata tag "blue6" of player to gold block
        set slot 24 of metadata tag "blue6" of player to unbreakable leather helmet of protection 3 with hidden enchants flag with hidden attributes flag named "&9Knight's Helmet" with lore "&3Protection 3" and "&3Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "blue6" of player to paper named "&c&lＰＡＧＥ &c5" with custom model data 1014
        set slot 44 of metadata tag "blue6" of player to paper named "&a&lＰＡＧＥ &a7" with custom model data 1013
        open (metadata tag "blue6" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue6" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft5"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft7"

command /bluecraft7:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue7" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue7" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "blue7" of player to iron block
        set slot 12 of metadata tag "blue7" of player to iron block
        set slot 13 of metadata tag "blue7" of player to iron block
        set slot 20 of metadata tag "blue7" of player to diamond block
        set slot 21 of metadata tag "blue7" of player to diamond chestplate
        set slot 22 of metadata tag "blue7" of player to diamond block
        set slot 29 of metadata tag "blue7" of player to gold block
        set slot 30 of metadata tag "blue7" of player to gold block
        set slot 31 of metadata tag "blue7" of player to gold block
        set slot 24 of metadata tag "blue7" of player to unbreakable leather chestplate of protection 3 with hidden enchants flag with hidden attributes flag named "&9Knight's Chestplate" with lore "&3Protection 3" and "&3Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "blue7" of player to paper named "&c&lＰＡＧＥ &c6" with custom model data 1014
        set slot 44 of metadata tag "blue7" of player to paper named "&a&lＰＡＧＥ &a8" with custom model data 1013
        open (metadata tag "blue7" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue7" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft6"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft8"

command /bluecraft8:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue8" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue8" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "blue8" of player to diamond block
        set slot 20 of metadata tag "blue8" of player to diamond
        set slot 21 of metadata tag "blue8" of player to diamond leggings
        set slot 22 of metadata tag "blue8" of player to diamond
        set slot 29 of metadata tag "blue8" of player to gold block
        set slot 30 of metadata tag "blue8" of player to iron block
        set slot 31 of metadata tag "blue8" of player to gold block
        set slot 24 of metadata tag "blue8" of player to unbreakable leather leggings of protection 3 with hidden enchants flag with hidden attributes flag named "&9Knight's Leggings" with lore "&3Protection 3" and "&3Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "blue8" of player to paper named "&c&lＰＡＧＥ &c7" with custom model data 1014
        set slot 44 of metadata tag "blue8" of player to paper named "&a&lＰＡＧＥ &a9" with custom model data 1013
        open (metadata tag "blue8" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue8" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft7"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft9"

command /bluecraft9:
    permission: recipes.blue
    permission message: &cNeed To Be Blue Team!
    trigger:
        wait 1 tick
        set metadata tag "blue9" of player to chest inventory with 5 rows named "&9&lＢＬＵＥ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "blue9" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "blue9" of player to diamond block
        set slot 20 of metadata tag "blue9" of player to iron block
        set slot 21 of metadata tag "blue9" of player to diamond boots
        set slot 22 of metadata tag "blue9" of player to iron block
        set slot 30 of metadata tag "blue9" of player to gold block
        set slot 24 of metadata tag "blue9" of player to unbreakable leather boots of protection 3 with hidden enchants flag with hidden attributes flag named "&9Knight's Boots" with lore "&3Protection 3" and "&3Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "blue9" of player to paper named "&c&lＰＡＧＥ &c8" with custom model data 1014
        open (metadata tag "blue9" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "blue9" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/bluecraft8"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /greencraft1:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green1" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green1" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "green1" of player to emerald
        set slot 12 of metadata tag "green1" of player to iron block
        set slot 13 of metadata tag "green1" of player to emerald
        set slot 20 of metadata tag "green1" of player to diamond block
        set slot 21 of metadata tag "green1" of player to diamond sword
        set slot 22 of metadata tag "green1" of player to diamond block
        set slot 29 of metadata tag "green1" of player to emerald
        set slot 30 of metadata tag "green1" of player to gold block
        set slot 31 of metadata tag "green1" of player to emerald
        set slot 24 of metadata tag "green1" of player to unbreakable netherite sword of sharpness 1 with hidden enchants flag named "&aKnight's Sword" with lore "&2Best Sword!" with custom model data 10702
        set slot 44 of metadata tag "green1" of player to paper named "&a&lＰＡＧＥ &a2" with custom model data 1013
        open (metadata tag "green1" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green1" of player):
        cancel event 
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft2"

command /greencraft2:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green2" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green2" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "green2" of player to iron block
        set slot 13 of metadata tag "green2" of player to iron ingot
        set slot 20 of metadata tag "green2" of player to diamond block
        set slot 21 of metadata tag "green2" of player to bow
        set slot 22 of metadata tag "green2" of player to iron ingot
        set slot 30 of metadata tag "green2" of player to gold block
        set slot 31 of metadata tag "green2" of player to iron ingot
        set slot 24 of metadata tag "green2" of player to unbreakable bow of efficiency 1 with hidden enchants flag named "&aKnight's Bow" with lore "&2Infinity 1" and "&2Punch 1" with custom model data 1000
        set slot 36 of metadata tag "green2" of player to paper named "&c&lＰＡＧＥ &c1" with custom model data 1014
        set slot 44 of metadata tag "green2" of player to paper named "&a&lＰＡＧＥ &a3" with custom model data 1013
        open (metadata tag "green2" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green2" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft1"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft3"

command /greencraft3:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green3" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green3" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "green3" of player to emerald
        set slot 12 of metadata tag "green3" of player to iron ingot
        set slot 13 of metadata tag "green3" of player to emerald
        set slot 20 of metadata tag "green3" of player to iron ingot
        set slot 21 of metadata tag "green3" of player to shield
        set slot 22 of metadata tag "green3" of player to iron ingot
        set slot 29 of metadata tag "green3" of player to emerald
        set slot 30 of metadata tag "green3" of player to iron ingot
        set slot 31 of metadata tag "green3" of player to emerald
        set slot 24 of metadata tag "green3" of player to unbreakable shield of unbreaking 3 with hidden enchants flag named "&aGreen Shield" with lore "&2Best Shield" with custom model data 603
        set slot 36 of metadata tag "green3" of player to paper named "&c&lＰＡＧＥ &c2" with custom model data 1014
        set slot 44 of metadata tag "green3" of player to paper named "&a&lＰＡＧＥ &a4" with custom model data 1013
        open (metadata tag "green3" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green3" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft2"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft4"

command /greencraft4:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green4" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green4" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "green4" of player to iron nugget
        set slot 12 of metadata tag "green4" of player to iron nugget
        set slot 13 of metadata tag "green4" of player to iron nugget
        set slot 20 of metadata tag "green4" of player to wheat seeds
        set slot 21 of metadata tag "green4" of player to wheat seeds
        set slot 22 of metadata tag "green4" of player to wheat seeds
        set slot 29 of metadata tag "green4" of player to iron nugget
        set slot 30 of metadata tag "green4" of player to iron nugget
        set slot 31 of metadata tag "green4" of player to iron nugget
        set slot 24 of metadata tag "green4" of player to golden carrot named "&fIron Bread" with lore "&23 Hunger Bars" with custom model data 32279
        set slot 36 of metadata tag "green4" of player to paper named "&c&lＰＡＧＥ &c3" with custom model data 1014
        set slot 44 of metadata tag "green4" of player to paper named "&a&lＰＡＧＥ &a5" with custom model data 1013
        open (metadata tag "green4" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green4" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft3"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft5"

command /greencraft5:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green5" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green5" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "green5" of player to gold nugget
        set slot 12 of metadata tag "green5" of player to gold nugget
        set slot 13 of metadata tag "green5" of player to gold nugget
        set slot 20 of metadata tag "green5" of player to wheat seeds
        set slot 21 of metadata tag "green5" of player to wheat seeds                     
        set slot 22 of metadata tag "green5" of player to wheat seeds
        set slot 29 of metadata tag "green5" of player to gold nugget
        set slot 30 of metadata tag "green5" of player to gold nugget
        set slot 31 of metadata tag "green5" of player to gold nugget
        set slot 24 of metadata tag "green5" of player to cooked beef named "&6Gold Bread" with lore "&24 Hunger Bars" with custom model data 52479
        set slot 36 of metadata tag "green5" of player to paper named "&c&lＰＡＧＥ &c4" with custom model data 1014
        set slot 44 of metadata tag "green5" of player to paper named "&a&lＰＡＧＥ &a6" with custom model data 1013
        open (metadata tag "green5" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green5" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft4"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft6"

command /greencraft6:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green6" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green6" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "green6" of player to diamond block
        set slot 20 of metadata tag "green6" of player to iron block
        set slot 21 of metadata tag "green6" of player to diamond helmet
        set slot 22 of metadata tag "green6" of player to iron block
        set slot 30 of metadata tag "green6" of player to gold block
        set slot 24 of metadata tag "green6" of player to unbreakable leather helmet of protection 3 with hidden enchants flag with hidden attributes flag named "&aKnight's Helmet" with lore "&2Protection 3" and "&2Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "green6" of player to paper named "&c&lＰＡＧＥ &c5" with custom model data 1014
        set slot 44 of metadata tag "green6" of player to paper named "&a&lＰＡＧＥ &a7" with custom model data 1013
        open (metadata tag "green6" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green6" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft5"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft7"

command /greencraft7:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green7" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green7" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "green7" of player to iron block
        set slot 12 of metadata tag "green7" of player to iron block
        set slot 13 of metadata tag "green7" of player to iron block
        set slot 20 of metadata tag "green7" of player to diamond block
        set slot 21 of metadata tag "green7" of player to diamond chestplate
        set slot 22 of metadata tag "green7" of player to diamond block
        set slot 29 of metadata tag "green7" of player to gold block
        set slot 30 of metadata tag "green7" of player to gold block
        set slot 31 of metadata tag "green7" of player to gold block
        set slot 24 of metadata tag "green7" of player to unbreakable leather chestplate of protection 3 with hidden enchants flag with hidden attributes flag named "&aKnight's Chestplate" with lore "&2Protection 3" and "&2Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "green7" of player to paper named "&c&lＰＡＧＥ &c6" with custom model data 1014
        set slot 44 of metadata tag "green7" of player to paper named "&a&lＰＡＧＥ &a8" with custom model data 1013
        open (metadata tag "green7" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green7" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft6"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft8"

command /greencraft8:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green8" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green8" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "green8" of player to diamond block
        set slot 20 of metadata tag "green8" of player to diamond
        set slot 21 of metadata tag "green8" of player to diamond leggings
        set slot 22 of metadata tag "green8" of player to diamond
        set slot 29 of metadata tag "green8" of player to gold block
        set slot 30 of metadata tag "green8" of player to iron block
        set slot 31 of metadata tag "green8" of player to gold block
        set slot 24 of metadata tag "green8" of player to unbreakable leather leggings of protection 3 with hidden enchants flag with hidden attributes flag named "&aKnight's Leggings" with lore "&2Protection 3" and "&2Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "green8" of player to paper named "&c&lＰＡＧＥ &c7" with custom model data 1014
        set slot 44 of metadata tag "green8" of player to paper named "&a&lＰＡＧＥ &a9" with custom model data 1013
        open (metadata tag "green8" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green8" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft7"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft9"

command /greencraft9:
    permission: recipes.green
    permission message: &cNeed To Be Green Team!
    trigger:
        wait 1 tick
        set metadata tag "green9" of player to chest inventory with 5 rows named "&2&lＧＲＥＥＮ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "green9" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "green9" of player to diamond block
        set slot 20 of metadata tag "green9" of player to iron block
        set slot 21 of metadata tag "green9" of player to diamond boots
        set slot 22 of metadata tag "green9" of player to iron block
        set slot 30 of metadata tag "green9" of player to gold block
        set slot 24 of metadata tag "green9" of player to unbreakable leather boots of protection 3 with hidden enchants flag with hidden attributes flag named "&aKnight's Boots" with lore "&2Protection 3" and "&2Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "green9" of player to paper named "&c&lＰＡＧＥ &c8" with custom model data 1014
        open (metadata tag "green9" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "green9" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/greencraft8"
#----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
command /yellowcraft1:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow1" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow1" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "yellow1" of player to raw gold
        set slot 12 of metadata tag "yellow1" of player to iron block
        set slot 13 of metadata tag "yellow1" of player to raw gold
        set slot 20 of metadata tag "yellow1" of player to diamond block
        set slot 21 of metadata tag "yellow1" of player to diamond sword
        set slot 22 of metadata tag "yellow1" of player to diamond block
        set slot 29 of metadata tag "yellow1" of player to raw gold
        set slot 30 of metadata tag "yellow1" of player to gold block
        set slot 31 of metadata tag "yellow1" of player to raw gold
        set slot 24 of metadata tag "yellow1" of player to unbreakable netherite sword of sharpness 1 with hidden enchants flag named "&eKnight's Sword" with lore "&6Best Sword!" with custom model data 10702
        set slot 44 of metadata tag "yellow1" of player to paper named "&a&lＰＡＧＥ &a2" with custom model data 1013
        open (metadata tag "yellow1" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow1" of player):
        cancel event 
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft2"

command /yellowcraft2:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow2" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow2" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "yellow2" of player to iron block
        set slot 13 of metadata tag "yellow2" of player to iron ingot
        set slot 20 of metadata tag "yellow2" of player to diamond block
        set slot 21 of metadata tag "yellow2" of player to bow
        set slot 22 of metadata tag "yellow2" of player to iron ingot
        set slot 30 of metadata tag "yellow2" of player to gold block
        set slot 31 of metadata tag "yellow2" of player to iron ingot
        set slot 24 of metadata tag "yellow2" of player to unbreakable bow of efficiency 1 with hidden enchants flag named "&eKnight's Bow" with lore "&6Infinity 1" and "&6Punch 1" with custom model data 1000
        set slot 36 of metadata tag "yellow2" of player to paper named "&c&lＰＡＧＥ &c1" with custom model data 1014
        set slot 44 of metadata tag "yellow2" of player to paper named "&a&lＰＡＧＥ &a3" with custom model data 1013
        open (metadata tag "yellow2" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow2" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft1"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft3"

command /yellowcraft3:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow3" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow3" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "yellow3" of player to raw gold
        set slot 12 of metadata tag "yellow3" of player to iron ingot
        set slot 13 of metadata tag "yellow3" of player to raw gold
        set slot 20 of metadata tag "yellow3" of player to iron ingot
        set slot 21 of metadata tag "yellow3" of player to shield
        set slot 22 of metadata tag "yellow3" of player to iron ingot
        set slot 29 of metadata tag "yellow3" of player to raw gold
        set slot 30 of metadata tag "yellow3" of player to iron ingot
        set slot 31 of metadata tag "yellow3" of player to raw gold
        set slot 24 of metadata tag "yellow3" of player to unbreakable shield of unbreaking 3 with hidden enchants flag named "&eyellow Shield" with lore "&6Best Shield" with custom model data 604
        set slot 36 of metadata tag "yellow3" of player to paper named "&c&lＰＡＧＥ &c2" with custom model data 1014
        set slot 44 of metadata tag "yellow3" of player to paper named "&a&lＰＡＧＥ &a4" with custom model data 1013
        open (metadata tag "yellow3" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow3" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft2"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft4"

command /yellowcraft4:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow4" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow4" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "yellow4" of player to iron nugget
        set slot 12 of metadata tag "yellow4" of player to iron nugget
        set slot 13 of metadata tag "yellow4" of player to iron nugget
        set slot 20 of metadata tag "yellow4" of player to wheat seeds
        set slot 21 of metadata tag "yellow4" of player to wheat seeds
        set slot 22 of metadata tag "yellow4" of player to wheat seeds
        set slot 29 of metadata tag "yellow4" of player to iron nugget
        set slot 30 of metadata tag "yellow4" of player to iron nugget
        set slot 31 of metadata tag "yellow4" of player to iron nugget
        set slot 24 of metadata tag "yellow4" of player to golden carrot named "&fIron Bread" with lore "&63 Hunger Bars" with custom model data 32279
        set slot 36 of metadata tag "yellow4" of player to paper named "&c&lＰＡＧＥ &c3" with custom model data 1014
        set slot 44 of metadata tag "yellow4" of player to paper named "&a&lＰＡＧＥ &a5" with custom model data 1013
        open (metadata tag "yellow4" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow4" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft3"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft5"

command /yellowcraft5:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow5" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow5" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "yellow5" of player to gold nugget
        set slot 12 of metadata tag "yellow5" of player to gold nugget
        set slot 13 of metadata tag "yellow5" of player to gold nugget
        set slot 20 of metadata tag "yellow5" of player to wheat seeds
        set slot 21 of metadata tag "yellow5" of player to wheat seeds                     
        set slot 22 of metadata tag "yellow5" of player to wheat seeds
        set slot 29 of metadata tag "yellow5" of player to gold nugget
        set slot 30 of metadata tag "yellow5" of player to gold nugget
        set slot 31 of metadata tag "yellow5" of player to gold nugget
        set slot 24 of metadata tag "yellow5" of player to cooked beef named "&6Gold Bread" with lore "&64 Hunger Bars" with custom model data 52479
        set slot 36 of metadata tag "yellow5" of player to paper named "&c&lＰＡＧＥ &c4" with custom model data 1014
        set slot 44 of metadata tag "yellow5" of player to paper named "&a&lＰＡＧＥ &a6" with custom model data 1013
        open (metadata tag "yellow5" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow5" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft4"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft6"

command /yellowcraft6:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow6" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow6" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "yellow6" of player to diamond block
        set slot 20 of metadata tag "yellow6" of player to iron block
        set slot 21 of metadata tag "yellow6" of player to diamond helmet
        set slot 22 of metadata tag "yellow6" of player to iron block
        set slot 30 of metadata tag "yellow6" of player to gold block
        set slot 24 of metadata tag "yellow6" of player to unbreakable leather helmet of protection 3 with hidden enchants flag with hidden attributes flag named "&eKnight's Helmet" with lore "&6Protection 3" and "&6Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "yellow6" of player to paper named "&c&lＰＡＧＥ &c5" with custom model data 1014
        set slot 44 of metadata tag "yellow6" of player to paper named "&a&lＰＡＧＥ &a7" with custom model data 1013
        open (metadata tag "yellow6" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow6" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft5"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft7"

command /yellowcraft7:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow7" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow7" of player to black stained glass pane named "&7"
        set slot 11 of metadata tag "yellow7" of player to iron block
        set slot 12 of metadata tag "yellow7" of player to iron block
        set slot 13 of metadata tag "yellow7" of player to iron block
        set slot 20 of metadata tag "yellow7" of player to diamond block
        set slot 21 of metadata tag "yellow7" of player to diamond chestplate
        set slot 22 of metadata tag "yellow7" of player to diamond block
        set slot 29 of metadata tag "yellow7" of player to gold block
        set slot 30 of metadata tag "yellow7" of player to gold block
        set slot 31 of metadata tag "yellow7" of player to gold block
        set slot 24 of metadata tag "yellow7" of player to unbreakable leather chestplate of protection 3 with hidden enchants flag with hidden attributes flag named "&eKnight's Chestplate" with lore "&6Protection 3" and "&6Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "yellow7" of player to paper named "&c&lＰＡＧＥ &c6" with custom model data 1014
        set slot 44 of metadata tag "yellow7" of player to paper named "&a&lＰＡＧＥ &a8" with custom model data 1013
        open (metadata tag "yellow7" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow7" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft6"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft8"

command /yellowcraft8:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow8" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow8" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "yellow8" of player to diamond block
        set slot 20 of metadata tag "yellow8" of player to diamond
        set slot 21 of metadata tag "yellow8" of player to diamond leggings
        set slot 22 of metadata tag "yellow8" of player to diamond
        set slot 29 of metadata tag "yellow8" of player to gold block
        set slot 30 of metadata tag "yellow8" of player to iron block
        set slot 31 of metadata tag "yellow8" of player to gold block
        set slot 24 of metadata tag "yellow8" of player to unbreakable leather leggings of protection 3 with hidden enchants flag with hidden attributes flag named "&eKnight's Leggings" with lore "&6Protection 3" and "&6Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "yellow8" of player to paper named "&c&lＰＡＧＥ &c7" with custom model data 1014
        set slot 44 of metadata tag "yellow8" of player to paper named "&a&lＰＡＧＥ &a9" with custom model data 1013
        open (metadata tag "yellow8" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow8" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft7"
        if event-slot = 44:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft9"

command /yellowcraft9:
    permission: recipes.yellow
    permission message: &cNeed To Be Yellow Team!
    trigger:
        wait 1 tick
        set metadata tag "yellow9" of player to chest inventory with 5 rows named "&e&lＹＥＬＬＯＷ ＲＥＣＩＰＥＳ:" 
        set slot 0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,23,25,26,27,28,32,33,34,35,36,37,38,39,40,41,42,43 and 44 of metadata tag "yellow9" of player to black stained glass pane named "&7"
        set slot 12 of metadata tag "yellow9" of player to diamond block
        set slot 20 of metadata tag "yellow9" of player to iron block
        set slot 21 of metadata tag "yellow9" of player to diamond boots
        set slot 22 of metadata tag "yellow9" of player to iron block
        set slot 30 of metadata tag "yellow9" of player to gold block
        set slot 24 of metadata tag "yellow9" of player to unbreakable leather boots of protection 3 with hidden enchants flag with hidden attributes flag named "&eKnight's Boots" with lore "&6Protection 3" and "&6Diamond Armor" with custom model data 1000
        set slot 36 of metadata tag "yellow9" of player to paper named "&c&lＰＡＧＥ &c8" with custom model data 1014
        open (metadata tag "yellow9" of player) to player 
on inventory click:
    if event-inventory = (metadata tag "yellow9" of player):
        cancel event 
        if event-slot = 36:
            close player's inventory
            wait 1 tick
            execute player command "/yellowcraft8"